//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_TRIZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupiedSeats
    {
        public int Id { get; set; }
        public int Row { get; set; }
        public int Seat { get; set; }
        public int SessionId { get; set; }
    
        public virtual Sessions Sessions { get; set; }
    }
}
